# Generated by Django 3.1.6 on 2021-02-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
