# Generated by Django 3.1.6 on 2021-02-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_auto_20210204_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
