# Generated by Django 3.1.6 on 2021-02-08 18:14

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_auto_20210204_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
    ]
