# Generated by Django 3.1.6 on 2021-02-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_auto_20210208_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('grupoid', models.AutoField(db_column='GrupoID', primary_key=True, serialize=False)),
                ('qtd', models.IntegerField(db_column='Qtd')),
                ('grupo', models.CharField(db_column='Grupo', max_length=2)),
            ],
            options={
                'db_table': 'grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('recomendacaoid', models.AutoField(db_column='RecomendacaoID', primary_key=True, serialize=False)),
                ('qtd', models.IntegerField(db_column='Qtd')),
            ],
            options={
                'db_table': 'recomendacao',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
    ]
