# Generated by Django 3.1.6 on 2021-02-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_auto_20210209_1043'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
